### ISSUE TITLE
automatic running applications on hosts

### ISSUE THREAD

**Issue by ckyy5770** [doc-vu/pads#3]
For now, the pads will simply generate a Mininet topology and a list of commands. The user may type those commands in the Mininet Client in order to run their applications. This is fine when the experiment is in relatively small scale. But when there are a large number of applications that need to be deployed on the Mininet, it will be a huge issue that the user has to type a command every time they want to run an application. For example, in a publisher-subscriber-broker system, if we have one publisher running on host1, and one broker running host2, and 20 subscribers running on host3. The user may expect the pads also generate a script that automatically runs those applications. I wrote a code snippet for this purpose:

```
def runApps(net):
    "Run cmds in command.txt"
    print "Running applications"
    with open("command.txt") as f:
        for line in f:
            splitedLine = line.split(' ', 1)
            print splitedLine[0]
            host = net.get(splitedLine[0])
            print splitedLine[1]
            host.cmd(splitedLine[1])
```
and our generated commands.txt should look like this:

```
h0 ./runBroker.sh &> ./result/h0broker0.log
h1 ./runPub.sh 10.0.0.1 &> ./result/h1pub0.log
h2 ./runSub.sh 10.0.0.1 &> ./result/h2sub0.log
h2 ./runSub.sh 10.0.0.1 &> ./result/h2sub1.log
h2 ./runSub.sh 10.0.0.1 &> ./result/h2sub2.log
...
...
```
Notice that every command has an redirect command as a part of it. It's reasonable that every application running on the Mininet need a private place to save their output. We could use "hostName" + "instanceID" to make the logfile for every application unique. And user should not bother to pass a unique logfile name as one of the arguments for each of applications.

**Comment by yogeshVU** [comment]
@iloveyoukcl5770  IP address assignment to host  https://github.com/mininet/mininet/blob/master/examples/linuxrouter.py

**Comment by yogeshVU** [comment]
@iloveyoukcl5770 another source for setting ip address: https://github.com/saeenali/openvswitch/blob/master/topology.py

**Comment by ckyy5770** [comment]
Assigning ip address to a host turns out to be simpler than I thought, we could just pass it as a parameter when we add a host, like this:
```
 h1 = self.addHost('h1', ip='10.0.0.31')
```
Also, you could delete two "print" statements in my code snippet above, they are just for testing.

**Comment by ckyy5770** [comment]
Also, for now, if I create two publisher instance within one host, they have identical log file name like this:
```
h1 sh publisher.sh  &>./result/h1PublisherApp.log
h1 sh publisher.sh  &>./result/h1PublisherApp.log
```
I guess this is because you used the application name as their instance ID.

For small scale tests, the user could adjust application name manually to make instances different, but for larger scale test, I suggest you design an "application-group" component as we discussed, where we would like the user to provide the cmd to run one instance, and the number of instances they'd like to run on one host. Then we create multiple instances and pass the same arguments provided by the user, and **create a unique log file for each of the instance.**

**Comment by ckyy5770** [comment]
The only difference between an "application-group"  and an "application" is the output in "command.txt". For example, for a Publisher application, we create one command for it:
```
h1 sh publisher.sh  &>./result/h1PublisherApp.log
```
while for a Publisher-group of two instances, we create two commands for it:
```
h1 sh publisher.sh  &>./result/h1PublisherAppGroup0.log
h1 sh publisher.sh  &>./result/h1PublisherAppGroup1.log
```
as you see, you can still use application name as a part of instance ID, but you have to add a number after it.

**Comment by yogeshVU** [comment]
@iloveyoukcl5770 can you please verify above changes if they work. thanks!

**Comment by ckyy5770** [comment]
I tested on my machine, there are some minor bugs, please make following changes:

1. for each command, add "&" at the end of the command and put a "space" between "&>" and "./...", and remove extra spaces between arguments (you usually put two spaces instead of one). a working command will be like this:
```
h3 sh ./runSub.sh 10.0.0.10 &> ./result/h3SubsriberApp1.log &
```
2. in the "topology.py", there is a syntax error at the last line of the code: use "#" instead of "//" to comment out a line in python.

3. put a sleep statement after the last line of "topology.py" and use net.stop() to clean up after each experiment, like so:
```
runApps(net)
sleep(30)
net.stop()
```
if a user doesn't want to specify a running time of the experiment, we could just sleep an extremely long time and catch interrupt exception from the user, then clean up using net.stop(). I don't know how to catch an interrupt exception using python, but I'm sure there should be a way to do this.

4. for now we don't have an application ID passing into each application, my experiment doesn't need it for single publisher/broker case. But it will be potentially required by others. I think you could just create one for each instance like what you did on log file, and just pass it automatically as the first parameter of the application. Or do it in a more flexible manner, for example, define a special marker, say "@INSTANCE_ID",  as a reserved word in user input cmd. Then you parse the cmd that the user provides, and replace "@INSTANCE_ID" with actually instance ID you generated for the user.

5. I did the basic test with revised "command.txt" and "topology.py", and it works well. You can find the source code of my applications and revised "command.txt", "topology.py" [here](https://github.com/doc-vu/simple-pub-sub-broker).

**Comment by ckyy5770** [comment]
Also, I added a statement in "runApps" to escape blank lines in "command.txt", and commented out two "print" statements.
```
def runApps(net):
    "Run cmds in command.txt"
    print "Running applications"
    with open("command.txt") as f:
        for line in f:
            if line == '\n':
                continue
            splitedLine = line.split(' ', 1)
            #print splitedLine[0]
            host = net.get(splitedLine[0])
            #print splitedLine[1]
            host.cmd(splitedLine[1])
```

**Comment by ckyy5770** [comment]
tested, no problem.

**Comment by yogeshVU** [comment]
thanks for your help! @iloveyoukcl5770
